// Code generated by Kitex v0.6.2. DO NOT EDIT.

package interactservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	"interact_service/biz"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	QueryFavoriteExist(ctx context.Context, Req *biz.QueryFavoriteExistReq, callOptions ...callopt.Option) (r *biz.QueryFavoriteExistResp, err error)
	QueryUserFavoriteVideoIds(ctx context.Context, Req *biz.FavoriteVideoReq, callOptions ...callopt.Option) (r *biz.FavoriteVideoResp, err error)
	CommentAction(ctx context.Context, Req *biz.CommentActionReq, callOptions ...callopt.Option) (r *biz.CommentActionResp, err error)
	CommentList(ctx context.Context, Req *biz.CommentListReq, callOptions ...callopt.Option) (r *biz.CommentListResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kInteractServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kInteractServiceClient struct {
	*kClient
}

func (p *kInteractServiceClient) QueryFavoriteExist(ctx context.Context, Req *biz.QueryFavoriteExistReq, callOptions ...callopt.Option) (r *biz.QueryFavoriteExistResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.QueryFavoriteExist(ctx, Req)
}

func (p *kInteractServiceClient) QueryUserFavoriteVideoIds(ctx context.Context, Req *biz.FavoriteVideoReq, callOptions ...callopt.Option) (r *biz.FavoriteVideoResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.QueryUserFavoriteVideoIds(ctx, Req)
}

func (p *kInteractServiceClient) CommentAction(ctx context.Context, Req *biz.CommentActionReq, callOptions ...callopt.Option) (r *biz.CommentActionResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CommentAction(ctx, Req)
}

func (p *kInteractServiceClient) CommentList(ctx context.Context, Req *biz.CommentListReq, callOptions ...callopt.Option) (r *biz.CommentListResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CommentList(ctx, Req)
}
