// Code generated by hertz generator.

package handler

import (
	"context"

	"client/dto"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Register .
// @router /internal/user/register [POST]
func Register(ctx context.Context, c *app.RequestContext) {
	var err error
	var req dto.UserRegisterReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(dto.UserRegisterResp)

	c.JSON(consts.StatusOK, resp)
}
