// Code generated by hertz generator.

package handler

import (
	"context"

	"client/dto"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// UserInfo .
// @router /internal/user/info [POST]
func UserInfo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req dto.UserInfoReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(dto.UserInfoResp)

	c.JSON(consts.StatusOK, resp)
}
