// Code generated by hertz generator.

package video_service

import (
	"context"
	"fmt"

	"github.com/cloudwego/hertz/pkg/common/config"
	"github.com/cloudwego/hertz/pkg/protocol"
	a "video_service/biz/model/a"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
)

type Client interface {
	Feed(context context.Context, req *a.FeedReq, reqOpt ...config.RequestOption) (resp *a.FeedResp, rawResponse *protocol.Response, err error)

	PublishVideo(context context.Context, req *a.PublishReq, reqOpt ...config.RequestOption) (resp *a.PublishResp, rawResponse *protocol.Response, err error)

	GetPublishList(context context.Context, req *a.GetPublishListReq, reqOpt ...config.RequestOption) (resp *a.GetPublishListResp, rawResponse *protocol.Response, err error)
}

type VideoServiceClient struct {
	client *cli
}

func NewVideoServiceClient(hostUrl string, ops ...Option) (Client, error) {
	opts := getOptions(append(ops, withHostUrl(hostUrl))...)
	cli, err := newClient(opts)
	if err != nil {
		return nil, err
	}
	return &VideoServiceClient{
		client: cli,
	}, nil
}

func (s *VideoServiceClient) Feed(context context.Context, req *a.FeedReq, reqOpt ...config.RequestOption) (resp *a.FeedResp, rawResponse *protocol.Response, err error) {
	httpResp := &a.FeedResp{}
	ret, err := s.client.r().
		setContext(context).
		setQueryParams(map[string]interface{}{}).
		setPathParams(map[string]string{}).
		setHeaders(map[string]string{}).
		setFormParams(map[string]string{}).
		setFormFileParams(map[string]string{}).
		setBodyParam(req).
		setRequestOption(reqOpt...).
		setResult(httpResp).
		execute("GET", "/internal/feed")
	if err != nil {
		return nil, nil, err
	}

	resp = httpResp
	rawResponse = ret.rawResponse
	return resp, rawResponse, nil
}

func (s *VideoServiceClient) PublishVideo(context context.Context, req *a.PublishReq, reqOpt ...config.RequestOption) (resp *a.PublishResp, rawResponse *protocol.Response, err error) {
	httpResp := &a.PublishResp{}
	ret, err := s.client.r().
		setContext(context).
		setQueryParams(map[string]interface{}{}).
		setPathParams(map[string]string{}).
		setHeaders(map[string]string{}).
		setFormParams(map[string]string{}).
		setFormFileParams(map[string]string{}).
		setBodyParam(req).
		setRequestOption(reqOpt...).
		setResult(httpResp).
		execute("POST", "/internal/video/publish")
	if err != nil {
		return nil, nil, err
	}

	resp = httpResp
	rawResponse = ret.rawResponse
	return resp, rawResponse, nil
}

func (s *VideoServiceClient) GetPublishList(context context.Context, req *a.GetPublishListReq, reqOpt ...config.RequestOption) (resp *a.GetPublishListResp, rawResponse *protocol.Response, err error) {
	httpResp := &a.GetPublishListResp{}
	ret, err := s.client.r().
		setContext(context).
		setQueryParams(map[string]interface{}{}).
		setPathParams(map[string]string{}).
		setHeaders(map[string]string{}).
		setFormParams(map[string]string{}).
		setFormFileParams(map[string]string{}).
		setBodyParam(req).
		setRequestOption(reqOpt...).
		setResult(httpResp).
		execute("GET", "/internal/video/list")
	if err != nil {
		return nil, nil, err
	}

	resp = httpResp
	rawResponse = ret.rawResponse
	return resp, rawResponse, nil
}

var defaultClient, _ = NewVideoServiceClient("")

func ConfigDefaultClient(ops ...Option) (err error) {
	defaultClient, err = NewVideoServiceClient("", ops...)
	return
}

func Feed(context context.Context, req *a.FeedReq, reqOpt ...config.RequestOption) (resp *a.FeedResp, rawResponse *protocol.Response, err error) {
	return defaultClient.Feed(context, req, reqOpt...)
}

func PublishVideo(context context.Context, req *a.PublishReq, reqOpt ...config.RequestOption) (resp *a.PublishResp, rawResponse *protocol.Response, err error) {
	return defaultClient.PublishVideo(context, req, reqOpt...)
}

func GetPublishList(context context.Context, req *a.GetPublishListReq, reqOpt ...config.RequestOption) (resp *a.GetPublishListResp, rawResponse *protocol.Response, err error) {
	return defaultClient.GetPublishList(context, req, reqOpt...)
}
