// Code generated by hertz generator.

package handler

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"relation_service/biz/model/client"
)

// GetFollowerList .
// @router /internal/relation/follower/list [GET]
func GetFollowerList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req client.RelationFollowerListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(client.RelationFollowerListResp)

	c.JSON(consts.StatusOK, resp)
}
