// Code generated by hertz generator.

package handler

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"relation_service/biz/model/client"
)

// GetFriendList .
// @router /internal/relation/friend/list [GET]
func GetFriendList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req client.RelationFriendListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(client.RelationFriendListResp)

	c.JSON(consts.StatusOK, resp)
}
