// Code generated by hertz generator.

package handler

import (
	"context"

	client "PinkTok/VideoService/biz/model/client"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// GetPublishList .
// @router /internal/video/list [GET]
func GetPublishList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req client.GetPublishListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(client.GetPublishListResp)

	c.JSON(consts.StatusOK, resp)
}
