// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"relation_service/biz/model"
	"relation_service/biz/mw/redis"
)

func main() {
	h := server.Default()

	register(h)
	model.InitDB()
	redis.InitRedis()
	h.Spin()
}
