// Code generated by hertz generator.

package handler

import (
	"context"

	dto "feed_service/biz/model/dto"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Feed .
// @router /internal/feed [GET]
func Feed(ctx context.Context, c *app.RequestContext) {
	var err error
	var req dto.FeedReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(dto.FeedResp)

	c.JSON(consts.StatusOK, resp)
}
