// Code generated by Kitex v0.6.2. DO NOT EDIT.

package relationservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	"relation_service/biz"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	SendRelationAction(ctx context.Context, Req *biz.RelationActionReq, callOptions ...callopt.Option) (r *biz.RelationActionResp, err error)
	GetFollowList(ctx context.Context, Req *biz.RelationFollowListReq, callOptions ...callopt.Option) (r *biz.RelationFollowListResp, err error)
	GetFollowerList(ctx context.Context, Req *biz.RelationFollowerListReq, callOptions ...callopt.Option) (r *biz.RelationFollowerListResp, err error)
	GetFriendList(ctx context.Context, Req *biz.RelationFriendListReq, callOptions ...callopt.Option) (r *biz.RelationFriendListResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kRelationServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kRelationServiceClient struct {
	*kClient
}

func (p *kRelationServiceClient) SendRelationAction(ctx context.Context, Req *biz.RelationActionReq, callOptions ...callopt.Option) (r *biz.RelationActionResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SendRelationAction(ctx, Req)
}

func (p *kRelationServiceClient) GetFollowList(ctx context.Context, Req *biz.RelationFollowListReq, callOptions ...callopt.Option) (r *biz.RelationFollowListResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetFollowList(ctx, Req)
}

func (p *kRelationServiceClient) GetFollowerList(ctx context.Context, Req *biz.RelationFollowerListReq, callOptions ...callopt.Option) (r *biz.RelationFollowerListResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetFollowerList(ctx, Req)
}

func (p *kRelationServiceClient) GetFriendList(ctx context.Context, Req *biz.RelationFriendListReq, callOptions ...callopt.Option) (r *biz.RelationFriendListResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetFriendList(ctx, Req)
}
