// Code generated by hertz generator.

package user_service

import (
	"context"
	"fmt"
	"user_service/biz/model/client"

	"github.com/cloudwego/hertz/pkg/common/config"
	"github.com/cloudwego/hertz/pkg/protocol"
)

// unused protection
var (
	_ = fmt.Formatter(nil)
)

type Client interface {
	Register(context context.Context, req *client.UserRegisterReq, reqOpt ...config.RequestOption) (resp *client.UserRegisterResp, rawResponse *protocol.Response, err error)

	Login(context context.Context, req *client.UserLoginReq, reqOpt ...config.RequestOption) (resp *client.UserLoginResp, rawResponse *protocol.Response, err error)

	UserInfo(context context.Context, req *client.UserInfoReq, reqOpt ...config.RequestOption) (resp *client.UserInfoResp, rawResponse *protocol.Response, err error)
}

type UserServiceClient struct {
	client *cli
}

func NewUserServiceClient(hostUrl string, ops ...Option) (Client, error) {
	opts := getOptions(append(ops, withHostUrl(hostUrl))...)
	cli, err := newClient(opts)
	if err != nil {
		return nil, err
	}
	return &UserServiceClient{
		client: cli,
	}, nil
}

func (s *UserServiceClient) Register(context context.Context, req *client.UserRegisterReq, reqOpt ...config.RequestOption) (resp *client.UserRegisterResp, rawResponse *protocol.Response, err error) {
	httpResp := &client.UserRegisterResp{}
	ret, err := s.client.r().
		setContext(context).
		setQueryParams(map[string]interface{}{}).
		setPathParams(map[string]string{}).
		setHeaders(map[string]string{}).
		setFormParams(map[string]string{}).
		setFormFileParams(map[string]string{}).
		setBodyParam(req).
		setRequestOption(reqOpt...).
		setResult(httpResp).
		execute("POST", "/internal/user/register")
	if err != nil {
		return nil, nil, err
	}

	resp = httpResp
	rawResponse = ret.rawResponse
	return resp, rawResponse, nil
}

func (s *UserServiceClient) Login(context context.Context, req *client.UserLoginReq, reqOpt ...config.RequestOption) (resp *client.UserLoginResp, rawResponse *protocol.Response, err error) {
	httpResp := &client.UserLoginResp{}
	ret, err := s.client.r().
		setContext(context).
		setQueryParams(map[string]interface{}{}).
		setPathParams(map[string]string{}).
		setHeaders(map[string]string{}).
		setFormParams(map[string]string{}).
		setFormFileParams(map[string]string{}).
		setBodyParam(req).
		setRequestOption(reqOpt...).
		setResult(httpResp).
		execute("POST", "/internal/user/login")
	if err != nil {
		return nil, nil, err
	}

	resp = httpResp
	rawResponse = ret.rawResponse
	return resp, rawResponse, nil
}

func (s *UserServiceClient) UserInfo(context context.Context, req *client.UserInfoReq, reqOpt ...config.RequestOption) (resp *client.UserInfoResp, rawResponse *protocol.Response, err error) {
	httpResp := &client.UserInfoResp{}
	ret, err := s.client.r().
		setContext(context).
		setQueryParams(map[string]interface{}{}).
		setPathParams(map[string]string{}).
		setHeaders(map[string]string{}).
		setFormParams(map[string]string{}).
		setFormFileParams(map[string]string{}).
		setBodyParam(req).
		setRequestOption(reqOpt...).
		setResult(httpResp).
		execute("POST", "/internal/user/info")
	if err != nil {
		return nil, nil, err
	}

	resp = httpResp
	rawResponse = ret.rawResponse
	return resp, rawResponse, nil
}

var defaultClient, _ = NewUserServiceClient("")

func ConfigDefaultClient(ops ...Option) (err error) {
	defaultClient, err = NewUserServiceClient("", ops...)
	return
}

func Register(context context.Context, req *client.UserRegisterReq, reqOpt ...config.RequestOption) (resp *client.UserRegisterResp, rawResponse *protocol.Response, err error) {
	return defaultClient.Register(context, req, reqOpt...)
}

func Login(context context.Context, req *client.UserLoginReq, reqOpt ...config.RequestOption) (resp *client.UserLoginResp, rawResponse *protocol.Response, err error) {
	return defaultClient.Login(context, req, reqOpt...)
}

func UserInfo(context context.Context, req *client.UserInfoReq, reqOpt ...config.RequestOption) (resp *client.UserInfoResp, rawResponse *protocol.Response, err error) {
	return defaultClient.UserInfo(context, req, reqOpt...)
}
