// Code generated by Kitex v0.6.2. DO NOT EDIT.

package userservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	"user_service/biz"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Register(ctx context.Context, Req *biz.UserRegisterReq, callOptions ...callopt.Option) (r *biz.UserRegisterResp, err error)
	Login(ctx context.Context, Req *biz.UserLoginReq, callOptions ...callopt.Option) (r *biz.UserLoginResp, err error)
	UserInfo(ctx context.Context, Req *biz.UserInfoReq, callOptions ...callopt.Option) (r *biz.UserInfoResp, err error)
	UserUpdate(ctx context.Context, Req *biz.UserUpdateReq, callOptions ...callopt.Option) (r *biz.UserUpdateResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kUserServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kUserServiceClient struct {
	*kClient
}

func (p *kUserServiceClient) Register(ctx context.Context, Req *biz.UserRegisterReq, callOptions ...callopt.Option) (r *biz.UserRegisterResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Register(ctx, Req)
}

func (p *kUserServiceClient) Login(ctx context.Context, Req *biz.UserLoginReq, callOptions ...callopt.Option) (r *biz.UserLoginResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Login(ctx, Req)
}

func (p *kUserServiceClient) UserInfo(ctx context.Context, Req *biz.UserInfoReq, callOptions ...callopt.Option) (r *biz.UserInfoResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UserInfo(ctx, Req)
}

func (p *kUserServiceClient) UserUpdate(ctx context.Context, Req *biz.UserUpdateReq, callOptions ...callopt.Option) (r *biz.UserUpdateResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UserUpdate(ctx, Req)
}
